### ISSUE TITLE
Command Spec.

### ISSUE THREAD

**Issue by 2ECC71** [loxtank/INTE-project#14]
## List of commands to implement:
- [ls](http://linuxcommand.org/man_pages/ls1.html)
- [mkdir](http://linuxcommand.org/man_pages/mkdir1.html)
- [grep](http://linuxcommand.org/man_pages/grep1.html)
- [cd](http://www.linfo.org/cd.html)
- [man](http://linuxcommand.org/man_pages/man1.html)

**Comment by etegan** [comment]
cd (byta mapp)
grep (söka efter sträng och skriv ut de rader där strängen förekommer)
ls (lista filer och mappar)
pwd (skriv ut nuvarande mapp)
touch (skapa fil)
mkdir (skapa mapp)
rm (ta bort mapp eller fil)
cat (skriv ut innehållet i en fil)
clear (rensa skärmen)
echo (skriv ut text)
mv (flytta fil eller mapp)

**Comment by 2ECC71** [comment]
Ja men det är väll bra! Vi kan ju göra två issues av dom och dela upp commandona på 2 olika sprints. 
Vilka är viktigast för grundläggande funktionalitet, kan vi rangordna dom?

**Comment by 2ECC71** [comment]
Det verkar som att grep är knepigast att implementera. Jag gissar att man får använda en BufferedReader (https://docs.oracle.com/javase/tutorial/essential/io/file.html) och iterera över BufferedReader.readline() och kolla om linen innehåller den sökta strängen.

**Comment by etegan** [comment]
Såhär gjorde jag när jag skulle läsa in alla platser på PROG2:

```
Path path = Paths.get(filePath);
List<String> placeStrings = Files.readAllLines(path);
return placeStrings.stream().map(s -> factory.createPlace(s.trim().split(","))).collect(Collectors.toCollection(ArrayList::new));   
```

Går ju att göra samma sak bara att lambda-funtionen söker igenom raden efter texten

**Comment by 2ECC71** [comment]
Nice, men verkar som att det är bättre att använda: FIles.lines() istället för File.readAllLines() för att inte crasha på väldigt stora filer. Se nedan:

A better way to read a text file line by line in Java 8 is by using Files.lines() method which take advantage of Stream API introduced in Java 8. This method is lazy and only reads lines when some terminal operation is performed on Stream e.g. when you call forEach() method to display lines from the file or call count() method to calculate a total number of lines from a file.

Read more: http://javarevisited.blogspot.com/2015/07/3-ways-to-read-file-line-by-line-in.html#ixzz4J2c5kGnH
